version: "3.8"

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/go/src/app/"
    depends_on:
      - postgres
    env_file: .env
  postgres:
    image: postgres:12.4-alpine
    environment:
     POSTGRES_USER: postgres
     POSTGRES_HOST_AUTH_METHOD: trust
    ports:
     - "5432:5432"
